var map_config = {
	'default':{
		'borderColor':'#9CA8B6', //country outlines
		'lakesColor':'#EBECED', // lakes color #66CCFF
		'mapShadow':'#000', //shadow color below the map
		'shadowOpacity':'50', //shadow opacity, value, 0-100
		'hoverShadow':'#666666', //tooltip shadow color
	},
	'map_1':{
		'hover': 'ALGERIA',  //country hover content
		'url':'http://www.html5interactivemaps.com/', //Goto URL
		'target':'same_window', //open link in new window:new_window, open in current window:same_window, or none for nothing.
		'upColor':'#EBECED', //country color when page loads
		'overColor':'#FFEE88', //country color when mouse hover
		'downColor':'#993366',//country color when mouse clicking
		'enable':false,//false/false to enable/disable this country
	},
	'map_2':{
		'hover': 'ANGOLA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_3':{
		'hover': 'BENIN',
		'url':'http://devguslists.com/bj',
		'target':'same_window',
		'upColor':'#FFEE88',
		'overColor':'#F56200',
		'downColor':'#993366',
		'enable':true,
	},
	'map_4':{
		'hover': 'BOTSWANA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_5':{
		'hover': 'BURKINA FASO',
		'url':'http://devguslists.com/bf',
		'target':'same_window',
		'upColor':'#FFEE88',
		'overColor':'#F56200',
		'downColor':'#993366',
		'enable':true,
	},
	'map_6':{
		'hover': 'BURUNDI',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_7':{
		'hover': 'CAMEROON',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_8':{
		'hover': 'CENTRAL AFRICAN REPUBLIC',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_9':{
		'hover': 'CHAD',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_10':{
		'hover': 'COMOROS',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_11':{
		'hover': 'CONGO',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_12':{
		'hover': 'CÔTE D&#39;IVOIRE',
		'url':'http://devguslists.com/ci',
		'target':'same_window',
		'upColor':'#FFEE88',
		'overColor':'#F56200',
		'downColor':'#993366',
		'enable':true,
	},
	'map_13':{
		'hover': 'DEMOCRATIC REPUBLIC OF THE CONGO',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_14':{
		'hover': 'DJIBOUTI',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_15':{
		'hover': 'EGYPT',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_16':{
		'hover': 'EQUATORIAL GUINEA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_17':{
		'hover': 'ERITREA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_18':{
		'hover': 'ETHIOPIA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_19':{
		'hover': 'GABON',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_20':{
		'hover': 'GHANA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_21':{
		'hover': 'GUINEA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_22':{
		'hover': 'GUINEA-BISSAU',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_23':{
		'hover': 'KENYA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_24':{
		'hover': 'LESOTHO',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_25':{
		'hover': 'LIBERIA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_26':{
		'hover': 'LIBYA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_27':{
		'hover': 'MADAGASCAR',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_28':{
		'hover': 'MALAWI',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_29':{
		'hover': 'MALI',
		'url':'http://devguslists.com/ml',
		'target':'same_window',
		'upColor':'#FFEE88',
		'overColor':'#F56200',
		'downColor':'#993366',
		'enable':true,
	},
	'map_30':{
		'hover': 'MAURITANIA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_31':{
		'hover': 'MAURITIUS',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_32':{
		'hover': 'MOROCCO',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_33':{
		'hover': 'MOZAMBIQUE',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_34':{
		'hover': 'NAMIBIA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_35':{
		'hover': 'NIGER',
		'url':'http://devguslists.com/ne',
		'target':'same_window',
		'upColor':'#FFEE88',
		'overColor':'#F56200',
		'downColor':'#993366',
		'enable':true,
	},
	'map_36':{
		'hover': 'NIGERIA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_37':{
		'hover': 'RWANDA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_38':{
		'hover': 'SENEGAL',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_39':{
		'hover': 'SEYCHELLES',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_40':{
		'hover': 'SIERRA LEONE',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_41':{
		'hover': 'SOMALIA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_42':{
		'hover': 'SOUTH AFRICA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_43':{
		'hover': 'SOUTH SUDAN',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_44':{
		'hover': 'SUDAN',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_45':{
		'hover': 'SWAZILAND',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_46':{
		'hover': 'SÃO TOMÉ AND PRÍNCIPE',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_47':{
		'hover': 'TANZANIA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_48':{
		'hover': 'THE GAMBIA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_49':{
		'hover': 'TOGO',
		'url':'http://devguslists.com/tg',
		'target':'same_window',
		'upColor':'#FFEE88',
		'overColor':'#F56200',
		'downColor':'#993366',
		'enable':true,
	},
	'map_50':{
		'hover': 'TUNISIA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_51':{
		'hover': 'UGANDA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_52':{
		'hover': 'WESTERN SAHARA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_53':{
		'hover': 'ZAMBIA',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
	'map_54':{
		'hover': 'ZIMBABWE',
		'url':'http://www.html5interactivemaps.com/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#FFEE88',
		'downColor':'#993366',
		'enable':false,
	},
}
